# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
image: docker:20.10.5
services:
  - docker:20.10.5-dind
stages:
  - build-push

before_script:
  - echo $CI_REGISTRY_USER
  - echo $CI_COMMIT_REF_NAME
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin

latest-build-push-job:
  stage: build-push
  only:
    - master
  script:
    - docker build -t antonseliverstof/devops-test-app:latest .
    - docker push antonseliverstof/devops-test-app:latest

tag-build-push-job:
  stage: build-push
  only:
    - tags
  script:
    - docker build -t antonseliverstof/devops-test-app:$CI_COMMIT_REF_NAME .
    - docker push antonseliverstof/devops-test-app:$CI_COMMIT_REF_NAME
