apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 31499
  selector:
    app: test-app