apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-app
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: antonseliverstof/devops-test-app:latest
        imagePullPolicy: ifNotPresent
        ports:
        - containerPort: 80
          name: http